# Generated by Django 5.0.3 on 2024-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taxonID", models.IntegerField()),
                ("acceptedNameUsageID", models.IntegerField()),
                ("parentNameUsageID", models.IntegerField()),
                ("originalNameUsageID", models.IntegerField()),
                ("scientificName", models.CharField(max_length=255)),
                ("acceptedNameUsage", models.CharField(max_length=255)),
                ("parentNameUsage", models.CharField(max_length=255)),
                ("namePublishedIn", models.CharField(max_length=255)),
                ("namePublishedInYear", models.IntegerField()),
                ("higherClassification", models.CharField(max_length=255)),
                ("kingdom", models.CharField(max_length=255)),
                ("phylum", models.CharField(max_length=255)),
                ("class_field", models.CharField(db_column="class", max_length=255)),
                ("order", models.CharField(max_length=255)),
                ("family", models.CharField(max_length=255)),
                ("genus", models.CharField(max_length=255)),
                ("specificEpithet", models.CharField(max_length=255)),
                ("infraspecificEpithet", models.CharField(max_length=255)),
                ("taxonRank", models.CharField(max_length=255)),
                ("scientificNameAuthorship", models.CharField(max_length=255)),
                ("taxonomicStatus", models.CharField(max_length=255)),
                ("nomenclaturalStatus", models.CharField(max_length=255)),
                ("modified", models.DateTimeField()),
                ("bibliographicCitation", models.TextField()),
                ("references", models.TextField()),
            ],
        ),
    ]
