# Generated by Django 5.0.3 on 2025-06-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltaxon',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='id',
            new_name='uuid',
        ),
    ]
