# Generated by Django 5.0.3 on 2024-03-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxon",
            name="class_field",
        ),
        migrations.AddField(
            model_name="taxon",
            name="classe",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="acceptedNameUsage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="acceptedNameUsageID",
            field=models.IntegerField(verbose_name="ID do Nome Aceito"),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="bibliographicCitation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="family",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="genus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="higherClassification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="infraspecificEpithet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="kingdom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="namePublishedIn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="namePublishedInYear",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="nomenclaturalStatus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="order",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="originalNameUsageID",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="parentNameUsage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="parentNameUsageID",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="phylum",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="references",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="scientificName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="scientificNameAuthorship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="specificEpithet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="taxonID",
            field=models.IntegerField(verbose_name="ID na Taxonomia"),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="taxonRank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="taxonomicStatus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
