# Generated by Django 5.0.3 on 2025-10-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxon',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
