# Generated by Django 5.0.3 on 2024-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0002_remove_taxon_class_field_taxon_classe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="acceptedNameUsageID",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID do Nome Aceito"
            ),
        ),
    ]
