# Generated by Django 5.0.3 on 2025-10-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0002_alter_historicaltaxon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxon',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('cadastro', 'Cadastro Novo'), ('edicao', 'Edição de Espécie')], default='cadastro', max_length=20),
        ),
        migrations.AddField(
            model_name='taxon',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('cadastro', 'Cadastro Novo'), ('edicao', 'Edição de Espécie')], default='cadastro', max_length=20),
        ),
    ]
