# Generated by Django 5.0.3 on 2025-06-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0002_rename_id_historicaltaxon_uuid_rename_id_taxon_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltaxon',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='uuid',
            new_name='id',
        ),
    ]
