# Generated by Django 5.0.3 on 2025-10-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0003_historicaltaxon_tipo_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxon',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('cadastro', 'Cadastro Novo'), ('edicao', 'Edição de Espécie'), ('Exclusão', 'Exclusão de Espécie')], default='cadastro', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('cadastro', 'Cadastro Novo'), ('edicao', 'Edição de Espécie'), ('Exclusão', 'Exclusão de Espécie')], default='cadastro', max_length=20),
        ),
    ]
