# Generated by Django 5.0.3 on 2025-06-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0003_rename_uuid_historicaltaxon_id_rename_uuid_taxon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxon',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
