# Generated by Django 5.0.3 on 2024-04-02 19:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0004_taxon_caule"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="caule1",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("curto", "Curto"),
                    ("alongado", "Alongado"),
                    ("aereo", "Aéreo"),
                    ("ND", "Não determinado"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
