# Generated by Django 5.0.3 on 2025-10-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0005_alter_historicaltaxon_tipo_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxon',
            name='tipo_solicitacao',
            field=models.CharField(blank=True, choices=[('cadastro', 'Cadastro Novo'), ('edicao', 'Edição de Espécie'), ('exclusao', 'Exclusão de Espécie')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='tipo_solicitacao',
            field=models.CharField(blank=True, choices=[('cadastro', 'Cadastro Novo'), ('edicao', 'Edição de Espécie'), ('exclusao', 'Exclusão de Espécie')], max_length=20, null=True),
        ),
    ]
