# Generated by Django 5.0.3 on 2024-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eriocaulaceae",
            "0006_estado_remove_taxon_caule1_taxon_chave_identificacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="estado",
            field=models.TextField(blank=True, null=True),
        ),
    ]
