# Generated by Django 5.0.3 on 2024-05-06 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0007_taxon_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxon",
            name="estados",
        ),
    ]
