# Generated by Django 5.0.3 on 2025-12-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0008_historicaltaxon_user_taxon_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosTaxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_taxon/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('localidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidade da Foto')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_taxon', to='eriocaulaceae.taxon')),
            ],
        ),
    ]
