# Generated by Django 5.0.3 on 2024-05-06 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0008_remove_taxon_estados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxon",
            name="distribuicao_biomas",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="distribuicoes_formacoes",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="endemismo",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="fitofisionomias",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="paises",
        ),
    ]
