# Generated by Django 5.0.3 on 2024-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0009_remove_taxon_distribuicao_biomas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="paises",
            field=models.TextField(blank=True, null=True),
        ),
    ]
