# Generated by Django 5.0.3 on 2025-12-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0009_fotostaxon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotosTaxon',
        ),
    ]
