# Generated by Django 5.0.3 on 2025-12-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0010_delete_fotostaxon'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxon',
            name='localidade_das_fotos',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição das Fotos'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='localidade_das_fotos',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição das Fotos'),
        ),
    ]
