# Generated by Django 5.0.3 on 2024-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0010_taxon_paises"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="distribuicao_biomas",
            field=models.TextField(blank=True, null=True),
        ),
    ]
