# Generated by Django 5.0.3 on 2024-05-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0011_taxon_distribuicao_biomas"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="distribuicoes_formacoes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
