# Generated by Django 5.0.3 on 2024-05-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0012_taxon_distribuicoes_formacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="fitofisionomias",
            field=models.TextField(blank=True, null=True),
        ),
    ]
