# Generated by Django 5.0.3 on 2024-05-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eriocaulaceae", "0013_taxon_fitofisionomias"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="endemismo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALGUM_PAIS", "Endêmica de algum país"),
                    ("ALGUM_ESTADO", "Endêmica (de algum ou alguns estados)"),
                    ("BIOMAS", "Endêmica de (biomas)"),
                    ("FITOFISIONOMIAS", "Endêmica de (fitofisionomias)"),
                    ("SERRA", "Endêmica de (alguma serra, formação geológica etc..)"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
    ]
