# Generated by Django 5.0.3 on 2025-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0014_taxon_endemismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
