# Generated by Django 5.0.3 on 2025-04-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0015_alter_taxon_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
