# Generated by Django 5.0.3 on 2025-04-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0016_taxon_identificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='identificador',
        ),
    ]
