# Generated by Django 5.0.3 on 2025-04-04 20:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0017_remove_taxon_identificador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTaxon',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('taxonID', models.IntegerField(verbose_name='ID na Taxonomia')),
                ('acceptedNameUsageID', models.IntegerField(blank=True, null=True, verbose_name='ID do Nome Aceito')),
                ('parentNameUsageID', models.IntegerField(blank=True, null=True)),
                ('originalNameUsageID', models.IntegerField(blank=True, null=True)),
                ('scientificName', models.CharField(blank=True, max_length=255, null=True)),
                ('acceptedNameUsage', models.CharField(blank=True, max_length=255, null=True)),
                ('parentNameUsage', models.CharField(blank=True, max_length=255, null=True)),
                ('namePublishedIn', models.CharField(blank=True, max_length=255, null=True)),
                ('namePublishedInYear', models.IntegerField(blank=True, null=True)),
                ('higherClassification', models.CharField(blank=True, max_length=255, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=255, null=True)),
                ('phylum', models.CharField(blank=True, max_length=255, null=True)),
                ('classe', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('genus', models.CharField(blank=True, max_length=255, null=True)),
                ('specificEpithet', models.CharField(blank=True, max_length=255, null=True)),
                ('infraspecificEpithet', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonRank', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_morfologica', models.TextField(blank=True, null=True, verbose_name='Descrição Morfológica')),
                ('chave_identificacao', models.TextField(blank=True, null=True, verbose_name='Chave de Identificação')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentários')),
                ('estado', models.TextField(blank=True, null=True)),
                ('paises', models.TextField(blank=True, null=True)),
                ('distribuicao_biomas', models.TextField(blank=True, null=True)),
                ('fitofisionomias', models.TextField(blank=True, null=True)),
                ('distribuicoes_formacoes', models.TextField(blank=True, null=True)),
                ('endemismo', models.CharField(blank=True, choices=[('ALGUM_PAIS', 'Endêmica de algum país'), ('ALGUM_ESTADO', 'Endêmica (de algum ou alguns estados)'), ('BIOMAS', 'Endêmica de (biomas)'), ('FITOFISIONOMIAS', 'Endêmica de (fitofisionomias)'), ('SERRA', 'Endêmica de (alguma serra, formação geológica etc..)')], max_length=1000, null=True)),
                ('conservacao', models.CharField(blank=True, choices=[('EXTINTA', 'Extinta'), ('EXTINTA_NATUREZA', 'Extinta na natureza'), ('CRITICAMENTE_PERIGO', 'Criticamente em Perigo'), ('PERIGO', 'Em Perigo'), ('VULNERAVEL', 'Vulnerável'), ('QUASE_AMEACADA', 'Quase ameaçada'), ('MENOS_PREOCUPAMENTE', 'Menos preocupante'), ('NAO_AVALIADA', 'Não avaliada quanto ao grau de ameaça'), ('INSUFICIENTES', 'Dados Insuficientes'), ('NAO_AMEACADA', 'Não ameaçada')], max_length=1000, null=True)),
                ('conservacao_fonte', models.TextField(blank=True, null=True, verbose_name='Fonte de Onde foi retirada a Informação da Conservação')),
                ('caule', models.CharField(blank=True, choices=[('curto', 'Curto'), ('alongado', 'Alongado'), ('aereo', 'Aéreo'), ('ND', 'Não determinado')], max_length=50, null=True)),
                ('scientificNameAuthorship', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomicStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('nomenclaturalStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('bibliographicCitation', models.TextField(blank=True, null=True, verbose_name='Referências Bibliográficas')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Outras Referências')),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical taxon',
                'verbose_name_plural': 'historical taxons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
