# Generated by Django 5.0.3 on 2025-04-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0018_historicaltaxon'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxon',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
