# Generated by Django 5.0.3 on 2025-04-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0019_historicaltaxon_status_taxon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxon',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
