# Generated by Django 5.0.3 on 2025-04-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eriocaulaceae', '0020_historicaltaxon_created_at_taxon_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaxon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='created_at',
        ),
    ]
