# Generated by Django 5.0.3 on 2025-04-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisador',
            name='cargo',
        ),
    ]
